"""initial tables

Revision ID: 8149c370bebe
Create Date: 2023-09-22 22:24:31.735901

"""
from typing import Sequence, Union

import sqlalchemy as sa
from geoalchemy2.types import Geometry

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8149c370bebe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table(
        "store",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("postcode", sa.String(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("location", Geometry(geometry_type="POINT", srid=4326), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_store_location", "store", ["location"], unique=False, postgresql_using="gist", if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_store_location", table_name="store", postgresql_using="gist")
    op.drop_table("store")
    # ### end Alembic commands ###
